export default function sitemap() {
  return [
    {
      url: 'https://mictoo.com',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1,
    },
    // Format landing pages
    {
      url: 'https://mictoo.com/transcribe-audio-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://mictoo.com/transcribe-mp3-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://mictoo.com/transcribe-video-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    // Keyword landing pages
    {
      url: 'https://mictoo.com/timestamped-transcription',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/free-srt-generator',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/business-transcription',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    // Format pages
    {
      url: 'https://mictoo.com/wav-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/m4a-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/flac-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mictoo.com/ogg-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mictoo.com/webm-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    // Use-case pages
    {
      url: 'https://mictoo.com/interview-transcription',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/podcast-transcription',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/lecture-transcription',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mictoo.com/meeting-transcription',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/zoom-transcription',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/voice-memo-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mictoo.com/youtube-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: 'https://mictoo.com/aac-to-text',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mictoo.com/how-to-compress-audio',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    // Long-tail use cases (pack #4)
    { url: 'https://mictoo.com/webinar-transcription',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/dictation-to-text',            lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/google-meet-transcription',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/teams-meeting-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/sermon-transcription',         lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    // Competitor comparison pages (low KD, high CPC long-tail)
    { url: 'https://mictoo.com/descript-alternative',         lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/fireflies-alternative',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/turboscribe-alternative',      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/otter-alternative',            lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/notta-alternative',            lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    // Language-specific transcription landing pages (US audience, very low KD)
    { url: 'https://mictoo.com/french-speech-to-text',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/spanish-audio-to-text',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/german-audio-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/multilingual-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Localized tool pages — Batch 1 (FR/DE/ES/RU × timestamped/srt/youtube)
    { url: 'https://mictoo.com/fr/timestamped-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/timestamped-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/timestamped-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/timestamped-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/fr/free-srt-generator',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/free-srt-generator',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/free-srt-generator',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/free-srt-generator',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/fr/youtube-to-text',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/youtube-to-text',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/youtube-to-text',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/youtube-to-text',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    // Localized use-case pages — Batch 2a (FR/DE/ES/RU × interview/meeting/zoom)
    { url: 'https://mictoo.com/fr/interview-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/interview-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/interview-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/interview-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/fr/meeting-transcription',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/meeting-transcription',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/meeting-transcription',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/meeting-transcription',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/fr/zoom-transcription',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/zoom-transcription',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/zoom-transcription',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/zoom-transcription',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    // Localized use-case pages — Batch 2b (FR/DE/ES/RU × google-meet/teams/voice-memo/webinar/sermon/dictation)
    { url: 'https://mictoo.com/fr/google-meet-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/google-meet-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/google-meet-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/google-meet-transcription',   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/teams-meeting-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/teams-meeting-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/teams-meeting-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/teams-meeting-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/voice-memo-to-text',          lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/voice-memo-to-text',          lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/voice-memo-to-text',          lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/voice-memo-to-text',          lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/webinar-transcription',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/webinar-transcription',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/webinar-transcription',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/webinar-transcription',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/sermon-transcription',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: 'https://mictoo.com/de/sermon-transcription',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: 'https://mictoo.com/es/sermon-transcription',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: 'https://mictoo.com/ru/sermon-transcription',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.65 },
    { url: 'https://mictoo.com/fr/dictation-to-text',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/dictation-to-text',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/dictation-to-text',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/dictation-to-text',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Localized format pages — Batch 3 (FR/DE/ES/RU × 9 formats)
    { url: 'https://mictoo.com/fr/transcribe-audio-to-text',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/de/transcribe-audio-to-text',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/es/transcribe-audio-to-text',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/ru/transcribe-audio-to-text',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/fr/transcribe-mp3-to-text',      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/de/transcribe-mp3-to-text',      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/es/transcribe-mp3-to-text',      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/ru/transcribe-mp3-to-text',      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/fr/transcribe-video-to-text',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/de/transcribe-video-to-text',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/es/transcribe-video-to-text',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/ru/transcribe-video-to-text',    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/fr/wav-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/wav-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/wav-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/wav-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/fr/m4a-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/m4a-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/m4a-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/m4a-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/fr/webm-to-text',                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/webm-to-text',                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/webm-to-text',                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/webm-to-text',                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/flac-to-text',                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/flac-to-text',                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/flac-to-text',                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/flac-to-text',                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/ogg-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/ogg-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/ogg-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/ogg-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/aac-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/aac-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/aac-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/aac-to-text',                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Localized comparison pages — Batch 4 (FR/DE/ES/RU × 5 comparisons)
    { url: 'https://mictoo.com/fr/descript-alternative',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/descript-alternative',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/descript-alternative',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/descript-alternative',        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/fireflies-alternative',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/fireflies-alternative',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/fireflies-alternative',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/fireflies-alternative',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/turboscribe-alternative',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/turboscribe-alternative',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/turboscribe-alternative',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/turboscribe-alternative',     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/otter-alternative',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/otter-alternative',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/otter-alternative',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/otter-alternative',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/fr/notta-alternative',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/de/notta-alternative',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/es/notta-alternative',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/ru/notta-alternative',           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    // Localized guide — Batch 5 (FR/DE/ES/RU × how-to-compress-audio)
    { url: 'https://mictoo.com/fr/how-to-compress-audio',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.55 },
    { url: 'https://mictoo.com/de/how-to-compress-audio',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.55 },
    { url: 'https://mictoo.com/es/how-to-compress-audio',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.55 },
    { url: 'https://mictoo.com/ru/how-to-compress-audio',       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.55 },
    // Localized use-case pages — FR
    { url: 'https://mictoo.com/fr/podcast-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/fr/lecture-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7  },
    { url: 'https://mictoo.com/fr/business-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7  },
    // Localized use-case pages — DE
    { url: 'https://mictoo.com/de/podcast-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/de/lecture-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7  },
    { url: 'https://mictoo.com/de/business-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7  },
    // Localized use-case pages — ES
    { url: 'https://mictoo.com/es/podcast-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/es/lecture-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7  },
    { url: 'https://mictoo.com/es/business-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7  },
    // Localized use-case pages — RU
    { url: 'https://mictoo.com/ru/podcast-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://mictoo.com/ru/lecture-transcription',  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7  },
    { url: 'https://mictoo.com/ru/business-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7  },
    // Language pages
    {
      url: 'https://mictoo.com/fr',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://mictoo.com/de',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://mictoo.com/es',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://mictoo.com/ru',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    { url: 'https://mictoo.com/it',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7},
    // Info pages — EN
    { url: 'https://mictoo.com/about',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.5 },
    { url: 'https://mictoo.com/contact', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.4 },
    { url: 'https://mictoo.com/privacy', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://mictoo.com/terms',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    // Info pages — FR
    { url: 'https://mictoo.com/fr/about',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.4 },
    { url: 'https://mictoo.com/fr/contact', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://mictoo.com/fr/privacy', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    { url: 'https://mictoo.com/fr/terms',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    // Info pages — DE
    { url: 'https://mictoo.com/de/about',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.4 },
    { url: 'https://mictoo.com/de/contact', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://mictoo.com/de/privacy', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    { url: 'https://mictoo.com/de/terms',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    // Info pages — ES
    { url: 'https://mictoo.com/es/about',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.4 },
    { url: 'https://mictoo.com/es/contact', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://mictoo.com/es/privacy', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    { url: 'https://mictoo.com/es/terms',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    // Info pages — RU
    { url: 'https://mictoo.com/ru/about',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.4 },
    { url: 'https://mictoo.com/ru/contact', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://mictoo.com/ru/privacy', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    { url: 'https://mictoo.com/ru/terms',   lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    // Italian locale — Tier 1 Fase A.1 (2026-05-16)
    { url: 'https://mictoo.com/it/timestamped-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/free-srt-generator', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/youtube-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/interview-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/meeting-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/zoom-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/google-meet-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/teams-meeting-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/voice-memo-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/webinar-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/sermon-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/dictation-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/transcribe-audio-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/transcribe-mp3-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/transcribe-video-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/wav-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/m4a-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/webm-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/flac-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/ogg-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/aac-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/descript-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/fireflies-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/turboscribe-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/otter-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/notta-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/how-to-compress-audio', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/podcast-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/lecture-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/business-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/it/about', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.4 },
    { url: 'https://mictoo.com/it/contact', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.3 },
    { url: 'https://mictoo.com/it/privacy', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.2 },
    { url: 'https://mictoo.com/it/terms', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.2 },
    // Portuguese locale — Tier 1 Fase A.2 (2026-05-16)
    { url: 'https://mictoo.com/pt/timestamped-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/free-srt-generator', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/youtube-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/interview-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/meeting-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/zoom-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/google-meet-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/teams-meeting-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/voice-memo-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/webinar-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/sermon-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/dictation-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/transcribe-audio-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/transcribe-mp3-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/transcribe-video-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/wav-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/m4a-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/webm-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/flac-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/ogg-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/aac-to-text', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/descript-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/fireflies-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/turboscribe-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/otter-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/notta-alternative', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/how-to-compress-audio', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/podcast-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/lecture-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt/business-transcription', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://mictoo.com/pt', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://mictoo.com/pt/about', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.4 },
    { url: 'https://mictoo.com/pt/contact', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.3 },
    { url: 'https://mictoo.com/pt/privacy', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.2 },
    { url: 'https://mictoo.com/pt/terms', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.2 },


  ]
}
