// Word document export — uses the `docx` library to build a .docx file
// programmatically. Word natively handles Unicode for all scripts (Cyrillic,
// CJK, Arabic, etc.), so unlike PDF we don't need to embed custom fonts.
//
// The document structure: small header with file name + provenance, then
// transcript paragraphs separated by blank lines. Pause-based paragraph
// splitting mirrors the in-app text editor.

import { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } from 'docx'

const PAUSE_THRESHOLD = 1.5 // seconds — same as toParagraphs() in UploadZone

// Re-split segments into paragraphs at pauses > PAUSE_THRESHOLD, exactly
// matching the textarea the user saw in the result UI. Falls back to the
// plain `text` if segments are missing.
function segmentsToParagraphTexts(segments, fallbackText) {
  if (!segments?.length) {
    return (fallbackText || '').split(/\n{2,}/).map((p) => p.trim()).filter(Boolean)
  }
  const paragraphs = []
  let buffer = []
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i]
    const text = (seg.text || '').trim()
    if (!text) continue
    if (i === 0) {
      buffer.push(text)
      continue
    }
    const prev = segments[i - 1]
    const gap = seg.start - prev.end
    if (gap > PAUSE_THRESHOLD) {
      paragraphs.push(buffer.join(' '))
      buffer = [text]
    } else {
      buffer.push(text)
    }
  }
  if (buffer.length) paragraphs.push(buffer.join(' '))
  return paragraphs
}

export async function buildDocx({ text, segments, fileName, language }) {
  const paragraphs = segmentsToParagraphTexts(segments, text)
  const displayName = fileName || 'audio'

  const titleP = new Paragraph({
    heading: HeadingLevel.TITLE,
    children: [new TextRun({ text: displayName, bold: true, size: 32 })],
  })

  const metaP = new Paragraph({
    children: [
      new TextRun({
        text:
          (language ? `Language: ${language}  ·  ` : '') +
          `Generated by Mictoo on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        italics: true,
        color: '64748B',
        size: 18,
      }),
    ],
    spacing: { after: 360 }, // pt × 20
  })

  const bodyParagraphs = paragraphs.map(
    (p) => new Paragraph({
      children: [new TextRun({ text: p, size: 22 })],
      spacing: { after: 200 },
    })
  )

  const doc = new Document({
    creator: 'Mictoo',
    title: displayName,
    description: 'Transcription generated by Mictoo (mictoo.com)',
    sections: [
      {
        properties: {},
        children: [titleP, metaP, ...bodyParagraphs],
      },
    ],
  })

  return Packer.toBuffer(doc)
}
