// Word document export — uses the `docx` library to build a .docx file
// programmatically. Word natively handles Unicode for all scripts (Cyrillic,
// CJK, Arabic, etc.), so unlike PDF we don't need to embed custom fonts.
//
// The document structure: small header with file name + provenance, then
// transcript paragraphs separated by blank lines. Pause-based paragraph
// splitting mirrors the in-app text editor.

import { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } from 'docx'

const PAUSE_THRESHOLD = 1.5 // seconds — same as toParagraphs() in UploadZone

// Re-split segments into paragraphs at pauses > PAUSE_THRESHOLD, exactly
// matching the textarea the user saw in the result UI. Falls back to the
// plain `text` if segments are missing.
function segmentsToParagraphTexts(segments, fallbackText) {
  if (!segments?.length) {
    return (fallbackText || '').split(/\n{2,}/).map((p) => p.trim()).filter(Boolean)
  }
  const paragraphs = []
  let buffer = []
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i]
    const text = (seg.text || '').trim()
    if (!text) continue
    if (i === 0) {
      buffer.push(text)
      continue
    }
    const prev = segments[i - 1]
    const gap = seg.start - prev.end
    if (gap > PAUSE_THRESHOLD) {
      paragraphs.push(buffer.join(' '))
      buffer = [text]
    } else {
      buffer.push(text)
    }
  }
  if (buffer.length) paragraphs.push(buffer.join(' '))
  return paragraphs
}

// Builds an optional AI-summary block. Returns an array of Paragraphs that
// can be spliced into the document body. Empty array when no summary is
// requested or the summary is blank.
function buildSummarySection(summary) {
  if (!summary) return []
  const hasSummaryText = !!summary.summary
  const hasKeyPoints = Array.isArray(summary.keyPoints) && summary.keyPoints.length > 0
  const hasActionItems = Array.isArray(summary.actionItems) && summary.actionItems.length > 0
  if (!hasSummaryText && !hasKeyPoints && !hasActionItems) return []

  const out = []

  out.push(new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text: 'AI Summary', bold: true, size: 26 })],
    spacing: { before: 200, after: 160 },
  }))

  if (hasSummaryText) {
    out.push(new Paragraph({
      children: [new TextRun({ text: summary.summary, size: 22 })],
      spacing: { after: 200 },
    }))
  }

  if (hasKeyPoints) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: 'Key Points', bold: true, size: 22 })],
      spacing: { before: 160, after: 100 },
    }))
    for (const point of summary.keyPoints) {
      out.push(new Paragraph({
        children: [new TextRun({ text: point, size: 22 })],
        bullet: { level: 0 },
        spacing: { after: 80 },
      }))
    }
  }

  if (hasActionItems) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: 'Action Items', bold: true, size: 22 })],
      spacing: { before: 160, after: 100 },
    }))
    for (const item of summary.actionItems) {
      out.push(new Paragraph({
        children: [new TextRun({ text: item, size: 22 })],
        bullet: { level: 0 },
        spacing: { after: 80 },
      }))
    }
  }

  return out
}

export async function buildDocx({ text, segments, fileName, language, summary }) {
  const paragraphs = segmentsToParagraphTexts(segments, text)
  const displayName = fileName || 'audio'

  const titleP = new Paragraph({
    heading: HeadingLevel.TITLE,
    children: [new TextRun({ text: displayName, bold: true, size: 32 })],
  })

  const metaP = new Paragraph({
    children: [
      new TextRun({
        text:
          (language ? `Language: ${language}  ·  ` : '') +
          `Generated by Mictoo on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        italics: true,
        color: '64748B',
        size: 18,
      }),
    ],
    spacing: { after: 360 }, // pt × 20
  })

  const summarySection = buildSummarySection(summary)
  const hasSummary = summarySection.length > 0
  const hasTranscript = paragraphs.length > 0

  // Only emit the "Transcript" heading when there's an actual transcript AND
  // a summary above it (i.e. user picked "Both"). For transcript-only the
  // body speaks for itself; for summary-only there's nothing to head.
  const transcriptHeading = hasSummary && hasTranscript
    ? [new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: 'Transcript', bold: true, size: 26 })],
        spacing: { before: 280, after: 160 },
      })]
    : []

  const bodyParagraphs = paragraphs.map(
    (p) => new Paragraph({
      children: [new TextRun({ text: p, size: 22 })],
      spacing: { after: 200 },
    })
  )

  const doc = new Document({
    creator: 'Mictoo',
    title: displayName,
    description: 'Transcription generated by Mictoo (mictoo.com)',
    sections: [
      {
        properties: {},
        children: [titleP, metaP, ...summarySection, ...transcriptHeading, ...bodyParagraphs],
      },
    ],
  })

  return Packer.toBuffer(doc)
}
